apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jupyter-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter
          image: jupyter/pyspark-notebook:latest
