apiVersion: v1
kind: Namespace
metadata:
  name: spark
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark
  namespace: spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: spark
---
apiVersion: v1
kind: Pod
metadata:
  name: jupyter
  namespace: spark
  labels:
    app: jupyter
spec:
  serviceAccountName: spark
  containers:
    - name: jupyter
      image: kanchishimono/pyspark-jupyter:latest
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  namespace: spark
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: jupyter
  ports:
    - name: default
      port: 8888
      protocol: TCP
      targetPort: 8888
