apiVersion: v1
kind: Namespace
metadata:
  name: spark-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
  namespace: spark-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-rb
  namespace: spark-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: spark-sa
    namespace: spark-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-dp
  namespace: spark-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      serviceAccountName: spark-sa
      containers:
        - name: jupyter
          image: jupyter/pyspark-notebook:63d0df23b673
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-svc
  namespace: spark-ns
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: jupyter
  ports:
    - name: default
      port: 8888
      protocol: TCP
      targetPort: 8888
