apiVersion: v1
kind: Namespace
metadata:
  name: spark-example
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
  namespace: spark-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-rb
  namespace: spark-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
  - kind: ServiceAccount
    name: spark-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-dp
  namespace: spark-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter
          image: jupyter/pyspark-notebook:latest
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-svc
  namespace: spark-example
spec:
  clusterIP: None
  ports:
    - name: default
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
  selector:
    app: jupyter
  type: ClusterIP

